language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"

script: bash release.sh test 5.0 x86

branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
