language: python

python:
  - "3.5"

sudo: required

services:
  - docker

install: "pip install -r requirements.txt"

script: bash travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
