version: "2.2"
services:
  hub:
    image: selenium/hub:3.4.0
    ports:
      - "4444:4444"

  node_samsung_7.1.1:
    image: butomo1989/docker-android-x86-7.1.1
    privileged: true
    scale: 2
    ports:
      - 6080
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - SELENIUM_HOST=hub

  node_nexus_web_7.1.1:
    image: butomo1989/docker-android-x86-7.1.1
    privileged: true
    scale: 2
    ports:
      - 6080
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - SELENIUM_HOST=hub
      - MOBILE_WEB_TEST=True
